More argument parsing fine-tuning
- Introduce the -x option (equivalent to --delete).
- Fix minor parsing problems.

diff --git a/homeclean b/homeclean
--- a/homeclean
+++ b/homeclean
@@ -8,37 +8,38 @@
 #     https://creativecommons.org/publicdomain/zero/1.0
 
 VERSION="1.0-beta"
+EXEC_NAME=$( basename $( readlink -f "$0" ) )
 
 # ERROR EXITS
 
 function exit_invalid_option() {
     echo "Invalid option '$1'."
-    echo "Invoke '-h' or '--help' for help."
+    echo "Try '$EXEC_NAME --help' for help."
     exit 1
 }
 
 function exit_requires() {
     echo "Option '$1' requires $2."
-    echo "Invoke '-h' or '--help' for help."
+    echo "Try '$EXEC_NAME --help' for help."
     exit 1
 }
 
 function exit_does_not_require() {
     echo "Option '$1' does not require a value."
-    echo "Invoke '-h' or '--help' for help."
+    echo "Try '$EXEC_NAME --help' for help."
     exit 1
 }
 
 function exit_generic_option() {
     echo "Generic option '$1' must not be used with other options."
-    echo "Invoke '-h' or '--help' for help."
+    echo "Try '$EXEC_NAME --help' for help."
     exit 1
 }
 
 # GENERIC OPTIONS
 
 [ $# -eq 1 ] && case "$1" in
-    "-h" | "--help")
+    "--help")
         echo -e "\
 homeclean - Clean your Linux computer's home directory.
 
@@ -47,19 +48,13 @@ Usage: homeclean GENERIC_OPTION
 
 Generic options:
 
-  -h, --help                Print this help.
-  -v, --version             Print this program's version.
+      --help                Print this help.
+      --version             Print this program's version.
 
 Options:
 
   -a, --not-accessed=N       Delete files that haven't been accessed in the last
                              N (default: 365) days.
-      --ignore=PATHS         Define an ignore pattern. PATHS can include
-                             multiple paths delimited by the colon (':') and
-                             each path can include wildcards. This overrides
-                             .homecleanignore.
-      --include=PATHS        Define an include pattern. This overrides
-                             .homecleaninclude.
       --ignore-hidden=TYPE   Ignore hidden files and directories. TYPE can be:
                                * 'all', to ignore all hidden items;
                                * 'root', to ignore hidden files and directories
@@ -70,11 +65,13 @@ Options:
   -N, --non-recursive        Search for files non-recursively.
   -I, --invert               Invert selection of files. Using this option twice
                              is the same as not using it.
-      --trash[=TRASH_PATH]   Move files to trash (default). If TRASH_PATH is
-                             set, use it instead of HOMECLEAN_TRASH.
-      --delete               Delete files permanently.
+      --trash[=PATH]         Move files to trash (default). If PATH is set, use
+                             it instead of HOMECLEAN_TRASH.
+  -x, --delete               Delete files permanently.
   -d, --dry                  Only print selection, do not trash or delete.
       --show-config          Only print configuration, do not trash or delete.
+      --export-config[=FILE] Export current configuration to FILE. If FILE isn't
+                             set, export to ~/.homecleanrc.
   -p, --preserve-hierarchy   Preserve directory hierarchy in trash (default).
   -l, --lose-hierarchy       Don't preserve the hierarchy in trash.
   -c, --cron                 Don't prompt. For use as a cronjob.
@@ -113,7 +110,7 @@ ALWAYS ignored: .bashrc, .bash_profile, .bash_logout, .bash_history"
         exit 0
         ;;
 
-    "-v" | "--version")
+    "--version")
         echo $VERSION
         exit 0
         ;;
@@ -131,20 +128,22 @@ HOMECLEAN_INVERT=false
 HOMECLEAN_BEHAVIOR="trash"
 HOMECLEAN_TRASH="$HOME/.homecleantrash"
 HOMECLEAN_TRASH_HIERARCHY="preserve"
-HOMECLEAN_IGNORE=""
-HOMECLEAN_INCLUDE="$HOME"
 HOMECLEAN_CRON=false
 
-# Variables that should not be exposted to the end-user
+# Private variables
 
 HOMECLEAN_SHOW_CONFIG=false
-HOMECLEAN_ALWAYS_IGNORE=".bashrc:.bash_profile:.bash_logout:.bash_history"
+HOMECLEAN_EXPORT_CONFIG=false
+HOMECLEAN_EXPORT_CONFIG_FILE="$HOME/.homecleanrc"
+HOMECLEAN_ALWAYS_IGNORE="\
+.bashrc
+.bash_profile
+.bash_logout
+.bash_history"
 
 # READ .homecleanrc
 
 [ -f "$HOME/.homecleanrc" ] && . "$HOME/.homecleanrc"
-
-HOMECLEAN_IGNORE="$HOMECLEAN_ALWAYS_IGNORE:$HOMECLEAN_IGNORE"
 
 # READ OPTIONS
 
@@ -156,40 +155,89 @@ do
 
         # Short options that require values
 
-        "-a"*)
-            value=${1#*a}
-            [[ -z "$value" ]] && value="$2" && shift
+        "-a")
 
-            [[ "$value" =~ ^\+?[0-9]+(\.[0-9]+)?$ ]] \
-                && HOMECLEAN_NOT_ACCESSED="$value"   \
+            [[ "$2" =~ ^\+?[0-9]+(\.[0-9]+)?$ ]]         \
+                && HOMECLEAN_NOT_ACCESSED="$2" && shift  \
                 || exit_requires "-a" "a positive number"
             ;;
 
-        # Short options that don't require values & long options
+        # Long options that require values
 
-        "--not-accessed="+)            HOMECLEAN_NOT_ACCESSED="${1#*=}";;
-        "--ignore="+)                  HOMECLEAN_IGNORE="${1#*=}";;
-        "--include="+)                 HOMECLEAN_INCLUDE="${1#*=}";;
-        "--ignore-hidden="+)           HOMECLEAN_IGNORE_HIDDEN="${1#*=}";;
-        "-R" | "--recursive")          HOMECLEAN_SEARCH_MODE="recursive";;
-        "-N" | "--non-recursive")      HOMECLEAN_SEARCH_MODE="non-recursive";;
+        "--not-accessed"?(=*))
+
+            [[ "${1#*=}" =~ ^\+?[0-9]+(\.[0-9]+)?$ ]]  \
+                && HOMECLEAN_NOT_ACCESSED="${1#*=}"    \
+                || exit_requires "--not-accessed" "a positive number"
+                ;;
+
+        "--ignore-hidden"?(=*))
+
+            [[ "${1#*=}" =~ ^(all|root|directories|files)$ ]]  \
+                && HOMECLEAN_IGNORE_HIDDEN="${1#*=}"           \
+                || exit_requires "--ignore-hidden" "a valid type"
+                ;;
+
+        "--trash="*)
+
+            HOMECLEAN_BEHAVIOR="trash"
+
+            [[ "${1#*=}" =~ ^[^\0]+$ ]]       \
+                && HOMECLEAN_TRASH="${1#*=}"  \
+                || exit_requires "--trash" "a path"
+            ;;
+
+        "--export-config="*)
+
+            HOMECLEAN_EXPORT_CONFIG=true
+
+            [[ "${1#*=}" =~ ^[^\0]+$ ]]                    \
+                && HOMECLEAN_EXPORT_CONFIG_FILE="${1#*=}"  \
+                || exit_requires "--export-config" "a path"
+            ;;
+
+        # Options that don't require values
+
+        "-R" | "--recursive"          ) HOMECLEAN_SEARCH_MODE="recursive";;
+        "-N" | "--non-recursive"      ) HOMECLEAN_SEARCH_MODE="non-recursive";;
         "-I" | "--invert")
             HOMECLEAN_INVERT=$(\
                 [ "$HOMECLEAN_INVERT" = true ] && echo "false" || echo "true" \
             );;
-        "--trash")                     HOMECLEAN_BEHAVIOR="trash";;
-        "--trash="+)                   HOMECLEAN_BEHAVIOR="trash"
-                                       HOMECLEAN_TRASH="${1#*=}";;
-        "--delete")                    HOMECLEAN_BEHAVIOR="delete";;
-        "-d" | "--dry")                HOMECLEAN_BEHAVIOR="dry";;
-        "--show-config")               HOMECLEAN_SHOW_CONFIG=true;;
-        "-p" | "--preserve-hierarchy") HOMECLEAN_TRASH_HIERARCHY="preserve";;
-        "-l" | "--lose-hierarchy")     HOMECLEAN_TRASH_HIERARCHY="lose";;
-        "-c" | "--cron")               HOMECLEAN_CRON=true;;
+               "--trash"              ) HOMECLEAN_BEHAVIOR="trash";;
+        "-x" | "--delete"             ) HOMECLEAN_BEHAVIOR="delete";;
+        "-d" | "--dry"                ) HOMECLEAN_BEHAVIOR="dry";;
+               "--show-config"        ) HOMECLEAN_SHOW_CONFIG=true;;
+               "--export-config"      ) HOMECLEAN_EXPORT_CONFIG=true;;
+        "-p" | "--preserve-hierarchy" ) HOMECLEAN_TRASH_HIERARCHY="preserve";;
+        "-l" | "--lose-hierarchy"     ) HOMECLEAN_TRASH_HIERARCHY="lose";;
+        "-c" | "--cron"               ) HOMECLEAN_CRON=true;;
+
+        # Special
+
+        "") break;;  # Skip empty arguments.
+        "--") shift && break;;  # End of options.
+
+        # Invalid options
+
+        "--help"?(=*) | "--version"?(=*))
+
+            exit_generic_option "$( echo "$1" | sed 's/=.*//' )";;
+
+        "--"@("not-accessed"|"ignore-hidden")?(=))
+
+            exit_requires "$( echo "$1" | sed 's/=.*//' )" "a value";;
+
+        "--"@("recursive"|"non-recursive"|"invert"|"delete"|"dry"|"show-config"\
+        |"preserve-hierarchy"|"lose-hierarchy"|"cron")"="*)
+
+            exit_does_not_require "$( echo "$1" | sed 's/=.*//' )";;
+
+        "--"+(?)) exit_invalid_option "$( echo "$1" | sed 's/=.*//' )";;
 
         # Shorthands
 
-        "-"+([RNIdplchv])?(a?(?("+")+([0-9])*(.+([0-9])))*))
+        "-"*([RNIxdplc])?(a?(?("+")+([0-9])*(.+([0-9])))*))
             for (( i = 1; i < ${#1}; i ++ ))
             do
                 case "${1:$i:1}" in
@@ -200,6 +248,7 @@ do
                             [ "$HOMECLEAN_INVERT" = true ]     \
                                 && echo "false" || echo "true" \
                         );;
+                    "x") HOMECLEAN_BEHAVIOR="delete";;
                     "d") HOMECLEAN_BEHAVIOR="dry";;
                     "p") HOMECLEAN_TRASH_HIERARCHY="preserve";;
                     "l") HOMECLEAN_TRASH_HIERARCHY="lose";;
@@ -215,48 +264,46 @@ do
                             exit_requires "-a" "a positive number"
                         fi
                         ;;
-                    "h" | "v")
-                        exit_generic_option "-${1:$i:1}"
-                        ;;
                 esac
             done
             ;;
 
-        # End of options symbol
+        # Invalid shorthands & arguments
 
-        "--") shift && break;;
+        "-"!(*([RNIxdplc])?(a?(?("+")+([0-9])*(.+([0-9])))*)))
 
-        # Invalid options
-
-        "-h" | "-v" | "--help"?(=*) | "--version"?(=*))
-            exit_generic_option "$( echo "$1" | sed 's/=.*//' )"
-            ;;
-
-        "--"@("not-accessed"|"not-created"|"ignore"|"include")?(=))
-            exit_requires "$( echo "$1" | sed 's/=.*//' )" "a value"
-            ;;
-
-        "--"@("recursive"|"non-recursive"|"invert"|"delete"|"dry"|"show-config"\
-        |"preserve-hierarchy"|"lose-hierarchy"|"cron")"="*)
-            exit_does_not_require "$( echo "$1" | sed 's/=.*//' )"
-            ;;
-
-        "-"!(+([RNIdplchv])?(a?(?("+")+([0-9])*(.+([0-9])))*)))
             for (( i = 1; i < ${#1}; i ++ ))
             do
-                if ! [[ "${1:$i:1}" =~ [RNIdplcahv] ]]
-                then
+                ! [[ "${1:$i:1}" =~ [RNIxdplca] ]] && \
                     exit_invalid_option "-${1:$i:1}"
-                fi
             done
             ;;
 
-        "") break;;
-        *) exit_invalid_option "$1";;
+        *)
+
+            echo "Invalid argument '$1'."
+            echo "Try '$EXEC_NAME --help' for help."
+            exit 1
+
     esac
 
     shift
 done
+
+# EXPORT CONFIG
+
+if [ "$HOMECLEAN_EXPORT_CONFIG" = true ]
+then
+    echo "\
+HOMECLEAN_NOT_ACCESSED=$HOMECLEAN_NOT_ACCESSED
+HOMECLEAN_IGNORE_HIDDEN=\"$HOMECLEAN_IGNORE_HIDDEN\"
+HOMECLEAN_SEARCH_MODE=\"$HOMECLEAN_SEARCH_MODE\"
+HOMECLEAN_INVERT=$HOMECLEAN_INVERT
+HOMECLEAN_BEHAVIOR=\"$HOMECLEAN_BEHAVIOR\"
+HOMECLEAN_TRASH=\"$HOMECLEAN_TRASH\"
+HOMECLEAN_TRASH_HIERARCHY=\"$HOMECLEAN_TRASH_HIERARCHY\"
+HOMECLEAN_CRON=$HOMECLEAN_CRON" > "$HOMECLEAN_EXPORT_CONFIG_FILE"
+fi
 
 # SHOW CONFIG
 
@@ -271,5 +318,6 @@ HOMECLEAN_BEHAVIOR         =  $HOMECLEAN_BEHAVIOR
 HOMECLEAN_TRASH            =  $HOMECLEAN_TRASH
 HOMECLEAN_TRASH_HIERARCHY  =  $HOMECLEAN_TRASH_HIERARCHY
 HOMECLEAN_CRON             =  $HOMECLEAN_CRON"
+
     exit 0
 fi
